/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as TopicsRouteImport } from './routes/topics'
import { Route as MissionRouteImport } from './routes/mission'
import { Route as LogRouteImport } from './routes/log'
import { Route as IntelRouteImport } from './routes/intel'
import { Route as IdeasRouteImport } from './routes/ideas'
import { Route as FocusRouteImport } from './routes/focus'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactsIndexRouteImport } from './routes/contacts.index'
import { Route as ContactsNewRouteImport } from './routes/contacts.new'
import { Route as ContactsIdRouteImport } from './routes/contacts.$id'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as ApiIngestRouteImport } from './routes/api/ingest'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsRoute = TopicsRouteImport.update({
  id: '/topics',
  path: '/topics',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionRoute = MissionRouteImport.update({
  id: '/mission',
  path: '/mission',
  getParentRoute: () => rootRouteImport,
} as any)
const LogRoute = LogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelRoute = IntelRouteImport.update({
  id: '/intel',
  path: '/intel',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasRoute = IdeasRouteImport.update({
  id: '/ideas',
  path: '/ideas',
  getParentRoute: () => rootRouteImport,
} as any)
const FocusRoute = FocusRouteImport.update({
  id: '/focus',
  path: '/focus',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsIndexRoute = ContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsNewRoute = ContactsNewRouteImport.update({
  id: '/contacts/new',
  path: '/contacts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsIdRoute = ContactsIdRouteImport.update({
  id: '/contacts/$id',
  path: '/contacts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIngestRoute = ApiIngestRouteImport.update({
  id: '/api/ingest',
  path: '/api/ingest',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/focus': typeof FocusRoute
  '/ideas': typeof IdeasRoute
  '/intel': typeof IntelRoute
  '/log': typeof LogRoute
  '/mission': typeof MissionRoute
  '/topics': typeof TopicsRoute
  '/upload': typeof UploadRoute
  '/api/ingest': typeof ApiIngestRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/contacts/$id': typeof ContactsIdRoute
  '/contacts/new': typeof ContactsNewRoute
  '/contacts/': typeof ContactsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/focus': typeof FocusRoute
  '/ideas': typeof IdeasRoute
  '/intel': typeof IntelRoute
  '/log': typeof LogRoute
  '/mission': typeof MissionRoute
  '/topics': typeof TopicsRoute
  '/upload': typeof UploadRoute
  '/api/ingest': typeof ApiIngestRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/contacts/$id': typeof ContactsIdRoute
  '/contacts/new': typeof ContactsNewRoute
  '/contacts': typeof ContactsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/focus': typeof FocusRoute
  '/ideas': typeof IdeasRoute
  '/intel': typeof IntelRoute
  '/log': typeof LogRoute
  '/mission': typeof MissionRoute
  '/topics': typeof TopicsRoute
  '/upload': typeof UploadRoute
  '/api/ingest': typeof ApiIngestRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/contacts/$id': typeof ContactsIdRoute
  '/contacts/new': typeof ContactsNewRoute
  '/contacts/': typeof ContactsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/focus'
    | '/ideas'
    | '/intel'
    | '/log'
    | '/mission'
    | '/topics'
    | '/upload'
    | '/api/ingest'
    | '/api/transcribe'
    | '/contacts/$id'
    | '/contacts/new'
    | '/contacts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/focus'
    | '/ideas'
    | '/intel'
    | '/log'
    | '/mission'
    | '/topics'
    | '/upload'
    | '/api/ingest'
    | '/api/transcribe'
    | '/contacts/$id'
    | '/contacts/new'
    | '/contacts'
  id:
    | '__root__'
    | '/'
    | '/focus'
    | '/ideas'
    | '/intel'
    | '/log'
    | '/mission'
    | '/topics'
    | '/upload'
    | '/api/ingest'
    | '/api/transcribe'
    | '/contacts/$id'
    | '/contacts/new'
    | '/contacts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FocusRoute: typeof FocusRoute
  IdeasRoute: typeof IdeasRoute
  IntelRoute: typeof IntelRoute
  LogRoute: typeof LogRoute
  MissionRoute: typeof MissionRoute
  TopicsRoute: typeof TopicsRoute
  UploadRoute: typeof UploadRoute
  ApiIngestRoute: typeof ApiIngestRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  ContactsIdRoute: typeof ContactsIdRoute
  ContactsNewRoute: typeof ContactsNewRoute
  ContactsIndexRoute: typeof ContactsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics': {
      id: '/topics'
      path: '/topics'
      fullPath: '/topics'
      preLoaderRoute: typeof TopicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission': {
      id: '/mission'
      path: '/mission'
      fullPath: '/mission'
      preLoaderRoute: typeof MissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log': {
      id: '/log'
      path: '/log'
      fullPath: '/log'
      preLoaderRoute: typeof LogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intel': {
      id: '/intel'
      path: '/intel'
      fullPath: '/intel'
      preLoaderRoute: typeof IntelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas': {
      id: '/ideas'
      path: '/ideas'
      fullPath: '/ideas'
      preLoaderRoute: typeof IdeasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/focus': {
      id: '/focus'
      path: '/focus'
      fullPath: '/focus'
      preLoaderRoute: typeof FocusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/': {
      id: '/contacts/'
      path: '/contacts'
      fullPath: '/contacts/'
      preLoaderRoute: typeof ContactsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/new': {
      id: '/contacts/new'
      path: '/contacts/new'
      fullPath: '/contacts/new'
      preLoaderRoute: typeof ContactsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/$id': {
      id: '/contacts/$id'
      path: '/contacts/$id'
      fullPath: '/contacts/$id'
      preLoaderRoute: typeof ContactsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ingest': {
      id: '/api/ingest'
      path: '/api/ingest'
      fullPath: '/api/ingest'
      preLoaderRoute: typeof ApiIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FocusRoute: FocusRoute,
  IdeasRoute: IdeasRoute,
  IntelRoute: IntelRoute,
  LogRoute: LogRoute,
  MissionRoute: MissionRoute,
  TopicsRoute: TopicsRoute,
  UploadRoute: UploadRoute,
  ApiIngestRoute: ApiIngestRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  ContactsIdRoute: ContactsIdRoute,
  ContactsNewRoute: ContactsNewRoute,
  ContactsIndexRoute: ContactsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
