ALTER TABLE public.contacts ADD COLUMN IF NOT EXISTS mode_tags TEXT[] NOT NULL DEFAULT '{}';
ALTER TABLE public.quotes ADD COLUMN IF NOT EXISTS mode TEXT NOT NULL DEFAULT 'dobot';
ALTER TABLE public.smart_topics ADD COLUMN IF NOT EXISTS mode TEXT NOT NULL DEFAULT 'dobot';